{{- if .Values.Istio.deploy_base_config }}
{{- $istio_namespace := .Values.global.namespace }}
################################
# Istio system namespace
################################
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $istio_namespace }}
---
{{- end }}
